version: '2'
services:
    motioneye:
        image: motioneye
        expose:
            - 8765
        environment:
            TIMEZONE: "Europe/Helsinki"
        privileged: true
        volumes:
            - /data-store:/var/lib/motion
            - /home/gorkh/workspace/motion/dockmotion/config/cameras/:/etc/motion/
            - /home/gorkh/tmp:/home/nobody/media
            - /home/gorkh/workspace/docker-motioneye/config:/config
            - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
        restart: 'always'

    front:
        image: front
        environment:
            TIMEZONE: "Europe/Helsinki"
        ports:
            - 8000:8000
        volumes_from:
            - motioneye
        restart: 'always'

